### ISSUE TITLE
The source code doesn't work on macOS

### ISSUE THREAD

**Issue by MaximeTAlgosup** [algosup/2023-2024-project-3-virtual-processor-team-4#20]
# Tested Version 
v0.0

## Description
The code doesn't run with a lot of errors on macOS.

## Steps
Download the source code and run main.c on macOS.

## Context
Found when testing the code on macOS while reviewing the pull request.

## Actual Result (optional screenshot)
![Screenshot 2024-02-13 at 14 42 36](https://github.com/algosup/2023-2024-project-3-virtual-processor-team-4/assets/145995586/cbf359c8-51de-4275-bc03-4427d374edbd)
%ld not recognize

## Security Criteria
4

## Discovery/Resolve Date
Discovery: 2/13/2024

## Expected Result
The code should run without any errors.

## Possible Solution
//

## Other
//

**Comment by TechXplorerFR** [comment]
The problem should have been fixed through [this commit](https://github.com/algosup/2023-2024-project-3-virtual-processor-team-4/commit/2ba2078b966fa2195d3ad09c850f5a8300e495b8).

The main problem was effectively linked to the %ld in lines as follows:

```c
printf("Error:` %s instruction does not accept first operand on line: %ld\n", opcode, *lineNumber);
```

As printing uint64_t numbers is not handled the same way across all OS, the code replacing the previous one is the following and includes PRIu64 macro:

```c
printf("Error: %s instruction does not accept first operand on line: %" PRIu64 "\n", opcode, *lineNumber);
```

**Comment by MaximeTAlgosup** [comment]
This issue was closed while the merge of the Pull Request: Merge of preprocessor to dev as of 12/2 #18.
