### ISSUE TITLE
Typo in Technical specification

### ISSUE THREAD

**Issue by MaximeTAlgosup** [algosup/2023-2024-project-3-virtual-processor-team-4#33]
## Description
Assembleur.c must be assembler.c

## Discovery/Resolve Date
02/20/24

**Comment by JasonGROSSO** [comment]
<img width="718" alt="Screenshot 2024-02-20 at 16 55 34" src="https://github.com/algosup/2023-2024-project-3-virtual-processor-team-4/assets/114397870/03e8291b-c6d4-433e-9249-801a1414efa4">

fixed
